// Generated by CoffeeScript 1.7.1

/*
// ==UserScript==
// @name           ATND Hatena Bookmarks for bookmarket
// @author         Yonchu
// @homepage       http://yonchu.hatenablog.com/
// @namespace      http://yonchu.hatenablog.com/
// @description    Show Hatena Bookmarks of articles in ATND
// @license        MIT License (http://opensource.org/licenses/MIT)
// @version        1.0.0
// @include        http://atnd.org/events/*
// @released       2013-06-14
// @updated        2013-06-14
// @compatible     Greasemonkey
// ==/UserScript==
// Version History:
//   1.0.0 - 2013/06/14 Release
 */

(function() {
  var addStyle, anchor, child, createHatebu, css, error, img, tagName, td, tr, trTags, url, _i, _j, _len, _len1, _ref;

  try {
    if (top !== self) {
      throw 0;
    }
  } catch (_error) {
    error = _error;
    return;
  }

  addStyle = function(css) {
    var head, style;
    if (typeof GM_addStyle !== "undefined" && GM_addStyle !== null) {
      GM_addStyle(css);
      return;
    }
    style = document.createElement('style');
    style.setAttribute('type', 'text/css');
    style.setAttribute('media', 'screen');
    style.appendChild(document.createTextNode(css));
    head = document.getElementsByTagName('head')[0];
    return head.appendChild(style);
  };

  createHatebu = (function() {
    var hatebuUrl, img_cache;
    hatebuUrl = 'http://b.st-hatena.com/entry/image/';
    img_cache = document.createElement('img');
    img_cache.className = 'hatebu';
    return function(url) {
      var img;
      img = img_cache.cloneNode();
      img.setAttribute('src', hatebuUrl + url);
      return img;
    };
  })();

  css = '.hatebu{padding-bottom: 2px !important; margin-left: 5px !important;}';

  addStyle(css);

  trTags = document.querySelectorAll('#post-body table tr');

  for (_i = 0, _len = trTags.length; _i < _len; _i++) {
    tr = trTags[_i];
    anchor = null;
    _ref = tr.children;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      td = _ref[_j];
      child = td.firstChild;
      if (!child) {
        continue;
      }
      tagName = child.tagName;
      if (!(tagName && tagName === 'a' || tagName === 'A')) {
        continue;
      }
      anchor = child;
      break;
    }
    if (!anchor) {
      continue;
    }
    url = anchor.href;
    if (!url) {
      continue;
    }
    img = createHatebu(url);
    td.appendChild(img);
  }

}).call(this);
